name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
loss:
  name: losses@ACTLossHead
  loss_type: softmax_cross_entropy

halt_exploration_prob: 0.0
halt_max_steps: 1

# 2 L_layers, 0 H_layers, cycled via H_cycles/L_cycles
# H_cycles=1, L_cycles=4, L_layers=2 → 1*4*2 = 8 effective passes
H_cycles: 1
L_cycles: 4

H_layers: 0
L_layers: 2

# Same width as 1M profile, scaled via additional experts (~10M params)
hidden_size: 64
num_heads: 1

expansion: 1  # Not used when use_moeut=True

puzzle_emb_ndim: 0

pos_encodings: rope
forward_dtype: float32

mlp_t: False
puzzle_emb_len: 0
no_ACT_continue: True
tie_word_embeddings: True

# MoE configuration targeting ~10M parameters
use_moeut: True

moe_ff_n_experts: 192
moe_ff_expert_size: 192
moe_ff_k: 2

moe_att_n_experts: 32
moe_att_k: 1

# Regularization and balancing (match 1M MoE config)
moe_expert_dropout: 0.0
#moe_entropy_reg: 0.01
#moe_att_entropy_reg: 0.001

moe_balance_coef: 0.0
moe_bias_balancing: True
moe_bias_update_rate: 0.001
moe_bias_momentum: 0.9
moe_bias_clip: 1.0
